version: '3'

services:
  video-streaming:
    image: go-video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: go-video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: 'no'
  video-storage:
    image: go-video-storage
    build:
      context: ./video-storage-azure
      dockerfile: Dockerfile
    container_name: go-video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: 'no'
