version: '3'

services:
  video-streaming:
    image: go-video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
      target: prod
    container_name: go-video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - METADATA_URL=http://metadata
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: 'no'

  video-storage:
    image: go-video-storage
    build:
      context: ./video-storage-azure
      dockerfile: Dockerfile
      target: prod
    container_name: go-video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: 'no'

  db:
    image: mongo:4.2
    container_name: go-db
    ports:
      - "4002:27017"
    restart: always

  history:
    image: go-history
    build:
      context: ./history
      dockerfile: Dockerfile
      target: prod
    container_name: go-history
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: 'no'

  rabbit:
    image: rabbitmq:3.8-management
    container_name: go-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    restart: always

  recommendations:
    image: go-recommendations
    build:
      context: ./recommendations
      dockerfile: Dockerfile
      target: prod
    container_name: go-recommendations
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: 'no'

  metadata:
    image: go-metadata
    build:
      context: ./metadata
      dockerfile: Dockerfile
      target: prod
    container_name: go-metadata
    ports:
      - "4005:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=metadata
    restart: 'no'

  gateway:
    image: go-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
      target: prod
    container_name: go-gateway
    ports:
      - "4006:80"
    environment:
      - PORT=80
      - METADATA_HOST=http://metadata
    restart: 'no'
    